export default {
  Arvo_Bold: 'Arvo-Bold',
  Arvo_BoldItalic: 'Arvo-BoldItalic',
  Arvo_Italic: 'Arvo-Italic',
  Arvo_Regular: 'Arvo-Regular',
  Lobster_Regular: 'Lobster-Regular',
  Lora_Italic_VariableFont_wght: 'Lora-Italic-VariableFont_wght',
  Lora_VariableFont_wght: 'Lora-VariableFont_wght',
  Pushster_Regular: 'Pushster-Regular',
  ZillaSlab_Bold: 'ZillaSlab-Bold',
  ZillaSlab_BoldItalic: 'ZillaSlab-BoldItalic',
  ZillaSlab_Italic: 'ZillaSlab-Italic',
  ZillaSlab_Light: 'ZillaSlab-Light',
  ZillaSlab_LightItalic: 'ZillaSlab-LightItalic',
  Poppins_Medium: 'Poppins-Medium',
  Ubuntu_Medium: 'Ubuntu-Medium',
};
